/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.views;

import main.java.Session;
import main.java.dao.RoleDao;
import main.java.dao.interfaces.IRoleDao;
import main.java.models.RoleModel;
import main.java.models.RoleTableModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.UIManager;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author yusuf
 */
public class RoleView extends javax.swing.JFrame {
    private final IRoleDao roleDao;

    /**
     * Creates new form CustomerView
     */
    public RoleView() {
        initComponents();
        this.roleDao = new RoleDao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        periodeTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        roleNameTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        roleIdTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        keywordTF = new javax.swing.JTextField();
        buttonClear = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ToHome = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nama");

        periodeTF.setPreferredSize(new java.awt.Dimension(400, 23));
        periodeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodeTFActionPerformed(evt);
            }
        });

        jLabel4.setText("Periode");

        roleNameTF.setPreferredSize(new java.awt.Dimension(400, 23));
        roleNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleNameTFActionPerformed(evt);
            }
        });

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        roleIdTF.setEnabled(false);
        roleIdTF.setPreferredSize(new java.awt.Dimension(400, 23));

        jLabel6.setText("ID");

        keywordTF.setPreferredSize(new java.awt.Dimension(400, 23));
        keywordTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keywordTFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                keywordTFMouseEntered(evt);
            }
        });
        keywordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordTFActionPerformed(evt);
            }
        });
        keywordTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keywordTFKeyReleased(evt);
            }
        });

        buttonClear.setText("Clear");
        buttonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClearMouseClicked(evt);
            }
        });

        buttonUpdate.setText("Ubah");
        buttonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonUpdateMouseClicked(evt);
            }
        });

        buttonDelete.setText("Hapus");
        buttonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDeleteMouseClicked(evt);
            }
        });
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonAdd.setText("Tambah");
        buttonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAddMouseClicked(evt);
            }
        });
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        jLabel7.setText("Cari Data");

        ToHome.setText("Home");
        ToHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToHomeMouseClicked(evt);
            }
        });
        ToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roleNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                            .addComponent(roleIdTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ToHome))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(57, 57, 57)
                        .addComponent(periodeTF, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keywordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(107, 107, 107)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(roleNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(periodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAdd)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonClear)
                        .addComponent(ToHome)
                        .addComponent(buttonDelete)
                        .addComponent(buttonUpdate)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(keywordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseClicked
        // TODO add your handling code here:
        String roleId = roleIdTF.getText();
        String roleName = roleNameTF.getText();
        String periode = periodeTF.getText();


        if(roleId.isEmpty()){
            if(roleName.isEmpty()){
                JOptionPane.showMessageDialog(null,"Nama Role tidak boleh kosong");
                roleNameTF.requestFocus();
            }else if(periode.isEmpty()){
                JOptionPane.showMessageDialog(null,"Periode tidak boleh kosong");
                periodeTF.requestFocus();
            }else{
                RoleModel dataRoleInsert = new RoleModel();
                dataRoleInsert.setName(roleName);
                dataRoleInsert.setPeriode(periode);
                
                RoleModel findOneRoleByName = roleDao.findOneByName(dataRoleInsert);
                if(findOneRoleByName != null){
                    JOptionPane.showMessageDialog(null,"Nama Role Sudah Ada");
                }else{
                 int insertRole = roleDao.create(dataRoleInsert);
                    if(insertRole > 0){
                        clearField();
                        keywordTF.setText("");
                        loadTable(null);
                        JOptionPane.showMessageDialog(null,"Berhasil Menambah Role");
                    }else{
                        JOptionPane.showMessageDialog(null,"Gagal Menambah Role");
                    }   
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"Tidak Bisa Menambah Role");
        }
       
    }//GEN-LAST:event_buttonAddMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        TableModel model = jTable1.getModel();
        String roleId = model.getValueAt(selectedRow, 0).toString();
        String roleName = model.getValueAt(selectedRow, 1).toString();
        String periode = model.getValueAt(selectedRow, 2).toString();
        
        roleIdTF.setText(roleId);
        roleNameTF.setText(roleName);
        periodeTF.setText(periode);
    }//GEN-LAST:event_jTable1MouseClicked

    private void buttonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClearMouseClicked
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_buttonClearMouseClicked

    private void buttonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDeleteMouseClicked
        // TODO add your handling code here:
        String roleId = roleIdTF.getText();
        if(!roleId.isEmpty()){
            int id = Integer.parseInt(roleId);
            int deleteRole = roleDao.delete(id);
            if(deleteRole == 1){
                clearField();
                loadTable(null); 
                JOptionPane.showMessageDialog(null,"Berhasil Hapus");
            }
        }
    }//GEN-LAST:event_buttonDeleteMouseClicked

    private void buttonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonUpdateMouseClicked
        // TODO add your handling code here:
        String roleId = roleIdTF.getText();
        String roleName = roleNameTF.getText();
        String periode = periodeTF.getText();
        
        if(!roleId.isEmpty()){
            if(roleName.isEmpty()){
                JOptionPane.showMessageDialog(null,"Nama Role tidak boleh kosong");
                roleNameTF.requestFocus();
            }else if(periode.isEmpty()){
                JOptionPane.showMessageDialog(null,"Periode tidak boleh kosong");
                periodeTF.requestFocus();
            }else{
                int id = Integer.parseInt(roleIdTF.getText());
                RoleModel dataUpdateRole = new RoleModel();
                dataUpdateRole.setName(roleName);
                dataUpdateRole.setPeriode(periode);
                dataUpdateRole.setId(id);
                
                RoleModel daoFindOneById = new RoleModel();
                daoFindOneById.setId(id);
                
                RoleModel previousRole = roleDao.findOneById(daoFindOneById);
                if(previousRole == null){
                    JOptionPane.showMessageDialog(null,"Role Tidak Ditemukan");
                }else{
                    if(previousRole.getName().equals(dataUpdateRole.getName())){
                        int updateRole = roleDao.update(dataUpdateRole);
                        if(updateRole > 0){
                            clearField();
                            loadTable(null);
                            JOptionPane.showMessageDialog(null,"Berhasil Mengubah Role");
                        }else{
                            JOptionPane.showMessageDialog(null,"Gagal Mengubah Role");
                        } 
                    }else{
                        RoleModel findOneRoleByName = roleDao.findOneByName(dataUpdateRole);
                        if(findOneRoleByName != null){
                            JOptionPane.showMessageDialog(null,"Nama Role Sudah Ada");
                        }else{
                            int updateDataRole = roleDao.update(dataUpdateRole);
                            if(updateDataRole > 0){
                                clearField();
                                loadTable(null);
                                JOptionPane.showMessageDialog(null,"Berhasil Mengubah Role");
                            }else{
                                JOptionPane.showMessageDialog(null,"Gagal Mengubah Role");
                            }   
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_buttonUpdateMouseClicked

    private void keywordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordTFActionPerformed

    private void keywordTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keywordTFKeyReleased
        // TODO add your handling code here:
        String keyword = keywordTF.getText();
        if(!keyword.equals("")){
            List<RoleModel> roles = roleDao.search(keyword);
            loadTable(roles);
        }else{
            loadTable(null);
        } 
    }//GEN-LAST:event_keywordTFKeyReleased

    private void keywordTFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keywordTFMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordTFMouseEntered

    private void keywordTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keywordTFMouseClicked
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_keywordTFMouseClicked

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void ToHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToHomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ToHomeMouseClicked

    private void ToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToHomeActionPerformed
        this.dispose();
        //menampilkan gui Menu
        new MenuView().start();
    }//GEN-LAST:event_ToHomeActionPerformed

    private void periodeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodeTFActionPerformed

    private void roleNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleNameTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoleView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ToHome;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField keywordTF;
    private javax.swing.JTextField periodeTF;
    private javax.swing.JTextField roleIdTF;
    private javax.swing.JTextField roleNameTF;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void dispose(){
        // TODO add your handling code here:
        roleDao.closeConnection();
        super.dispose();
    }
    
    public void start(){
        this.setTitle("Data Jabatan");
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setResizable(false); // fixed width
        this.setLocationRelativeTo(null); // Set JFrame to center of Screenn
        
        UIManager.put("OptionPane.yesButtonText", "Ya");
        UIManager.put("OptionPane.noButtonText", "Tidak");

        this.addWindowListener( new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JFrame frame = (JFrame)e.getSource();

                int result = JOptionPane.showConfirmDialog(
                    frame,
                    "Apakah Anda yakin ingin keluar dari aplikasi?",
                    "Keluar dari Aplikasi",
                    JOptionPane.YES_NO_OPTION);

                if (result == JOptionPane.YES_OPTION){
                    roleDao.closeConnection();
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    System.exit(0);
                }
            }
        });
        // TODO add your custom frame code here:
        loadTable(null);
       
        this.setVisible( true );
    }
    
    public void loadTable(List<RoleModel> roles) {
        if(roles == null){
            roles = roleDao.findAll();
        }
        RoleTableModel roleTableModel = new RoleTableModel(roles);
        
        jTable1.setModel(roleTableModel);
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTable1.getModel());
        jTable1.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
    }
    
    public void clearField(){
        roleNameTF.setText("");
        periodeTF.setText("");
        roleIdTF.setText("");
        keywordTF.setText("");
    }
}
