/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application.views;
import application.dao.CustomerDao;
import application.dao.interfaces.ICustomerDao;
import application.models.SegmentMarketModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

import javax.swing.JFrame;
import java.awt.Dimension;
import java.util.List;
/**
 *
 * @author she
 */
public class ChartView extends javax.swing.JFrame {
private final ICustomerDao customerDao;

    /**
     * Creates new form chartView
     */
    public ChartView() {
        initComponents();
        this.customerDao = new CustomerDao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChartView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public void start(){
        DefaultPieDataset dataset = new DefaultPieDataset();
        
        
        List<SegmentMarketModel> segmentsMarket = customerDao.getSegmentMarket();
         
         for (SegmentMarketModel segmentMarket : segmentsMarket) {
            dataset.setValue(segmentMarket.getSegmentName(), segmentMarket.getPercentage());
        }
//        dummy datas
//        dataset.setValue("Pharmaceutical", 12);
//        dataset.setValue("Foods & Beverages", 18);
//        dataset.setValue("Automotive Parts Industry", 8);
//        dataset.setValue("Pulp & Paper", 6);
//        dataset.setValue("Palm Oil Refinery", 9);
//        dataset.setValue("Steel Manufacturer", 15);
//        dataset.setValue("Water Process Company", 5);
//        dataset.setValue("MARINE/ Diesel", 7);
//        dataset.setValue("Power Plants", 10);
//        dataset.setValue("Water Cooling", 4);
//        dataset.setValue("Chemical", 6);
//        dataset.setValue("Oil & Gas", 10);

        JFreeChart chart = ChartFactory.createPieChart("Segment Market Share", dataset, true, true, false);

        PiePlot plot = (PiePlot) chart.getPlot();
        plot.setLabelGenerator(new StandardPieSectionLabelGenerator("{0}: {2}%"));

        JFrame frame = new JFrame("Chart Example");
        frame.setPreferredSize(new Dimension(500, 400));
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setResizable(false); // fixed width

        ChartPanel chartPanel = new ChartPanel(chart);
        frame.getContentPane().add(chartPanel);
        frame.pack();
        frame.setLocationRelativeTo(null); // Set JFrame to center of Screen
        frame.setVisible(true);
    }

}
