/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application.views;

import application.Session;
import application.dao.CustomerDao;
import application.dao.SegmentDao;
import application.dao.interfaces.ICustomerDao;
import application.models.CustomerModel;
import application.models.CustomerTableModel;
import application.models.SegmentModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author yusuf
 */
public class CustomerView extends javax.swing.JFrame {
    private final ICustomerDao customerDao;
    private final SegmentDao segmentDao;

    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
        initComponents();
        this.customerDao = new CustomerDao();
        this.segmentDao = new SegmentDao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        personInChargeTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customerNameTF = new javax.swing.JTextField();
        phoneNumberTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        customerIdTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        keywordTF = new javax.swing.JTextField();
        buttonClear = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nama");

        personInChargeTF.setPreferredSize(new java.awt.Dimension(400, 23));
        personInChargeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personInChargeTFActionPerformed(evt);
            }
        });

        jLabel3.setText("Segment");

        jLabel4.setText("Nama PIC");

        customerNameTF.setPreferredSize(new java.awt.Dimension(400, 23));

        phoneNumberTF.setPreferredSize(new java.awt.Dimension(400, 23));

        jLabel5.setText("No. Telp");

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        customerIdTF.setEnabled(false);
        customerIdTF.setPreferredSize(new java.awt.Dimension(400, 23));

        jLabel6.setText("ID");

        keywordTF.setPreferredSize(new java.awt.Dimension(400, 23));
        keywordTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keywordTFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                keywordTFMouseEntered(evt);
            }
        });
        keywordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordTFActionPerformed(evt);
            }
        });
        keywordTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keywordTFKeyReleased(evt);
            }
        });

        buttonClear.setText("Clear");
        buttonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClearMouseClicked(evt);
            }
        });

        buttonUpdate.setText("Ubah");
        buttonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonUpdateMouseClicked(evt);
            }
        });

        buttonDelete.setText("Hapus");
        buttonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDeleteMouseClicked(evt);
            }
        });

        buttonAdd.setText("Tambah");
        buttonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAddMouseClicked(evt);
            }
        });
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        jLabel7.setText("Cari Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personInChargeTF, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                            .addComponent(customerNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneNumberTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerIdTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonAdd)
                                .addGap(18, 18, 18)
                                .addComponent(buttonDelete)
                                .addGap(18, 18, 18)
                                .addComponent(buttonUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(buttonClear))
                            .addComponent(keywordTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(personInChargeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonUpdate)
                    .addComponent(buttonDelete)
                    .addComponent(buttonAdd)
                    .addComponent(buttonClear))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(keywordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseClicked
        // TODO add your handling code here:
        String customerId = customerIdTF.getText();
        String customerName = customerNameTF.getText();
        int selectedSegment = jComboBox2.getSelectedIndex();
        String pic = personInChargeTF.getText();
        String phoneNumber = phoneNumberTF.getText();

        if(customerId.isEmpty()){
            if(customerName.isEmpty()){
                JOptionPane.showMessageDialog(null,"Nama Customer tidak boleh kosong");
                customerNameTF.requestFocus();
            }else if(selectedSegment == 0){
                JOptionPane.showMessageDialog(null,"Segment tidak boleh kosong");
                jComboBox2.requestFocus();
            }else if(pic.isEmpty()){
                JOptionPane.showMessageDialog(null,"PIC Name tidak boleh kosong");
                personInChargeTF.requestFocus();
            }else if(phoneNumber.isEmpty()){
                JOptionPane.showMessageDialog(null,"No. Telp tidak boleh kosong");
                phoneNumberTF.requestFocus();
            }else{
                CustomerModel dataCustomerInsert = new CustomerModel();
                dataCustomerInsert.setName(customerName);
                dataCustomerInsert.setSegmentId(selectedSegment);
                dataCustomerInsert.setPersonInCharge(pic);
                dataCustomerInsert.setPhoneNumber(phoneNumber);
                
                CustomerModel findOneCustomerByName = customerDao.findOneByName(dataCustomerInsert);
                if(findOneCustomerByName != null){
                    JOptionPane.showMessageDialog(null,"Nama Customer Sudah Ada");
                }else{
                 int insertCustomer = customerDao.create(dataCustomerInsert);
                    if(insertCustomer > 0){
                        clearField();
                        loadTable(null);
                        JOptionPane.showMessageDialog(null,"Berhasil Menambah Customer");
                    }else{
                        JOptionPane.showMessageDialog(null,"Gagal Menambah Customer");
                    }   
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"Tidak Bisa Menambah Customer");
        }
       
    }//GEN-LAST:event_buttonAddMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        TableModel model = jTable1.getModel();
        String customerName = model.getValueAt(selectedRow, 1).toString();
        String segmentName = model.getValueAt(selectedRow, 2).toString();
        String pic = model.getValueAt(selectedRow, 3).toString();
        String phoneNumber = model.getValueAt(selectedRow, 4).toString();
        String customerId = model.getValueAt(selectedRow, 0).toString();
        
        customerNameTF.setText(customerName);
        jComboBox2.setSelectedItem(segmentName);
        personInChargeTF.setText(pic);
        phoneNumberTF.setText(phoneNumber);
        customerIdTF.setText(customerId);
    }//GEN-LAST:event_jTable1MouseClicked

    private void buttonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClearMouseClicked
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_buttonClearMouseClicked

    private void buttonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDeleteMouseClicked
        // TODO add your handling code here:
        String customerId = customerIdTF.getText();
        if(!customerId.isEmpty()){
            int id = Integer.parseInt(customerId);
            int deleteCustomer = customerDao.delete(id);
            if(deleteCustomer == 1){
                clearField();
                loadTable(null); 
                JOptionPane.showMessageDialog(null,"Berhasil Hapus");
            }
        }
    }//GEN-LAST:event_buttonDeleteMouseClicked

    private void buttonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonUpdateMouseClicked
        // TODO add your handling code here:
        String customerId = customerIdTF.getText();
        String customerName = customerNameTF.getText();
        int selectedSegment = jComboBox2.getSelectedIndex();
        String pic = personInChargeTF.getText();
        String phoneNumber = phoneNumberTF.getText();
        JOptionPane.showMessageDialog(null,customerId);
        if(!customerId.isEmpty()){
            if(customerName.isEmpty()){
                JOptionPane.showMessageDialog(null,"Nama Customer tidak boleh kosong");
                customerNameTF.requestFocus();
            }else if(selectedSegment == 0){
                JOptionPane.showMessageDialog(null,"Segment tidak boleh kosong");
                jComboBox2.requestFocus();
            }else if(pic.isEmpty()){
                JOptionPane.showMessageDialog(null,"PIC Name tidak boleh kosong");
                personInChargeTF.requestFocus();
            }else if(phoneNumber.isEmpty()){
                JOptionPane.showMessageDialog(null,"No. Telp tidak boleh kosong");
                phoneNumberTF.requestFocus();
            }else{
                int id = Integer.parseInt(customerIdTF.getText());
                CustomerModel dataUpdateCustomer = new CustomerModel();
                dataUpdateCustomer.setName(customerName);
                dataUpdateCustomer.setSegmentId(selectedSegment);
                dataUpdateCustomer.setPersonInCharge(pic);
                dataUpdateCustomer.setPhoneNumber(phoneNumber);
                dataUpdateCustomer.setId(id);
                
                CustomerModel daoFindOneById = new CustomerModel();
                daoFindOneById.setId(id);
                
                CustomerModel previousCustomer = customerDao.findOneById(daoFindOneById);
                if(previousCustomer == null){
                    JOptionPane.showMessageDialog(null,"Customer Tidak Ditemukan");
                }else{
                    if(previousCustomer.getName().equals(dataUpdateCustomer.getName())){
                        int updateCustomer = customerDao.update(dataUpdateCustomer);
                        if(updateCustomer > 0){
                            clearField();
                            loadTable(null);
                            JOptionPane.showMessageDialog(null,"Berhasil Mengubah Customer");
                        }else{
                            JOptionPane.showMessageDialog(null,"Gagal Mengubah Customer");
                        } 
                    }else{
                        CustomerModel findOneCustomerByName = customerDao.findOneByName(dataUpdateCustomer);
                        if(findOneCustomerByName != null){
                            JOptionPane.showMessageDialog(null,"Nama Customer Sudah Ada");
                        }else{
                            int updateDataCustomer = customerDao.update(dataUpdateCustomer);
                            if(updateDataCustomer > 0){
                                clearField();
                                loadTable(null);
                                JOptionPane.showMessageDialog(null,"Berhasil Mengubah Customer");
                            }else{
                                JOptionPane.showMessageDialog(null,"Gagal Mengubah Customer");
                            }   
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_buttonUpdateMouseClicked

    private void personInChargeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personInChargeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personInChargeTFActionPerformed

    private void keywordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordTFActionPerformed

    private void keywordTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keywordTFKeyReleased
        // TODO add your handling code here:
        String keyword = keywordTF.getText();
        if(!keyword.equals("")){
            List<CustomerModel> customers = customerDao.search(keyword);
            loadTable(customers);
        }else{
            loadTable(null);
        } 
    }//GEN-LAST:event_keywordTFKeyReleased

    private void keywordTFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keywordTFMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordTFMouseEntered

    private void keywordTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keywordTFMouseClicked
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_keywordTFMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JTextField customerIdTF;
    private javax.swing.JTextField customerNameTF;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField keywordTF;
    private javax.swing.JTextField personInChargeTF;
    private javax.swing.JTextField phoneNumberTF;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void dispose(){
        // TODO add your handling code here:
        customerDao.closeConnection();
        segmentDao.closeConnection();
        super.dispose();
    }
    
    public void start(){
        this.setTitle("Customer Master");
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setResizable(false); // fixed width
        this.setLocationRelativeTo(null); // Set JFrame to center of Screenn
        
        this.addWindowListener( new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JFrame frame = (JFrame)e.getSource();

                int result = JOptionPane.showConfirmDialog(
                    frame,
                    "Are you sure you want to exit the application?",
                    "Exit Application",
                    JOptionPane.YES_NO_OPTION);

                if (result == JOptionPane.YES_OPTION){
                    customerDao.closeConnection();
                    segmentDao.closeConnection();
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    System.exit(0);
                }
            }
        });
        // TODO add your custom frame code here:
        loadTable(null);
        loadComboBox();
       
        this.setVisible( true );
    }
    
    public void loadTable(List<CustomerModel> customers) {
        if(customers == null){
            customers = customerDao.findAll();
        }
        CustomerTableModel customerTableModel = new CustomerTableModel(customers);
        
        jTable1.setModel(customerTableModel);
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTable1.getModel());
        jTable1.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(3, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
    }
    
    public void loadComboBox(){
        List<SegmentModel> segments = segmentDao.findAll();
        segments.forEach(v -> {
            jComboBox2.addItem(v.getName());
        });
    }
    
    public void clearField(){
        customerNameTF.setText("");
        personInChargeTF.setText("");
        phoneNumberTF.setText("");
        jComboBox2.setSelectedIndex(0);
        customerIdTF.setText("");
    }
}
