/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application.views;

import application.Session;
import application.dao.EmployeeDao;
import application.dao.interfaces.IEmployeeDao;
import application.models.EmployeeModel;
import application.models.EmployeeTableModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author yusuf
 */
public class EmployeeView extends javax.swing.JFrame {
    private final IEmployeeDao employeeDao;

    /**
     * Creates new form EmployeeView
     */
    public EmployeeView() {
        initComponents();
        this.employeeDao = new EmployeeDao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        employeeNameTF = new javax.swing.JTextField();
        phoneNumberTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        employeeIdTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        keywordTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ToHome = new javax.swing.JButton();
        textAreaAddress = new java.awt.TextArea();
        jLabelTTL = new javax.swing.JLabel();
        birthDateTF = new javax.swing.JTextField();
        roleNameTF = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        joinDateTF = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        buttonAdd = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        panel3 = new java.awt.Panel();
        jLabelAddress = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelJoinDate = new javax.swing.JLabel();
        genderTF = new javax.swing.JTextField();
        birthPlaceTF = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nama");

        employeeNameTF.setPreferredSize(new java.awt.Dimension(400, 23));

        phoneNumberTF.setPreferredSize(new java.awt.Dimension(400, 23));

        jLabel5.setText("No. Telp");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        employeeIdTF.setEnabled(false);
        employeeIdTF.setPreferredSize(new java.awt.Dimension(400, 23));

        jLabel6.setText("ID");

        keywordTF.setPreferredSize(new java.awt.Dimension(400, 23));
        keywordTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keywordTFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                keywordTFMouseEntered(evt);
            }
        });
        keywordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordTFActionPerformed(evt);
            }
        });
        keywordTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keywordTFKeyReleased(evt);
            }
        });

        jLabel7.setText("Cari Data");

        ToHome.setText("Home");
        ToHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToHomeMouseClicked(evt);
            }
        });
        ToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToHomeActionPerformed(evt);
            }
        });

        jLabelTTL.setText("Tempat, Tgl Lahir");

        birthDateTF.setPreferredSize(new java.awt.Dimension(400, 23));

        roleNameTF.setPreferredSize(new java.awt.Dimension(400, 23));
        roleNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleNameTFActionPerformed(evt);
            }
        });

        jLabelStatus.setText("Jabatan");

        joinDateTF.setPreferredSize(new java.awt.Dimension(400, 23));
        joinDateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinDateTFActionPerformed(evt);
            }
        });

        buttonAdd.setText("Tambah");
        buttonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAddMouseClicked(evt);
            }
        });
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonDelete.setText("Hapus");
        buttonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDeleteMouseClicked(evt);
            }
        });
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonUpdate.setText("Ubah");
        buttonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonUpdateMouseClicked(evt);
            }
        });

        buttonClear.setText("Clear");
        buttonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(buttonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdd)
                    .addComponent(buttonDelete)
                    .addComponent(buttonUpdate)
                    .addComponent(buttonClear)))
        );

        jLabelAddress.setText("Alamat");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addComponent(jLabelAddress)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAddress)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabel3.setText("Jenis Kelamin");

        jLabelJoinDate.setText("Bergabung");

        genderTF.setPreferredSize(new java.awt.Dimension(400, 23));

        birthPlaceTF.setPreferredSize(new java.awt.Dimension(400, 23));
        birthPlaceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthPlaceTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabelTTL)
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(roleNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(employeeIdTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneNumberTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(employeeNameTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(birthPlaceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(birthDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelJoinDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(joinDateTF, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(textAreaAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(genderTF, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(keywordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(ToHome)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(ToHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeeIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(genderTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(112, 112, 112))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(employeeNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTTL)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(birthDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(birthPlaceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phoneNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(textAreaAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelStatus)
                                .addComponent(joinDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelJoinDate))
                            .addComponent(roleNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keywordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseClicked
        // TODO add your handling code here:
        String employeeId = employeeIdTF.getText();
        String employeeName = employeeNameTF.getText();
        String phoneNumber = phoneNumberTF.getText();

        if(employeeId.isEmpty()){
            if(employeeName.isEmpty()){
                JOptionPane.showMessageDialog(null,"Nama Employee tidak boleh kosong");
                employeeNameTF.requestFocus();
            }else if(phoneNumber.isEmpty()){
                JOptionPane.showMessageDialog(null,"No. Telp tidak boleh kosong");
                phoneNumberTF.requestFocus();
            }else{
                EmployeeModel dataEmployeeInsert = new EmployeeModel();
                dataEmployeeInsert.setName(employeeName);
                dataEmployeeInsert.setPhoneNumber(phoneNumber);
                
                EmployeeModel findOneEmployeeByName = employeeDao.findOneByName(dataEmployeeInsert);
                if(findOneEmployeeByName != null){
                    JOptionPane.showMessageDialog(null,"Nama Employee Sudah Ada");
                }else{
                 int insertEmployee = employeeDao.create(dataEmployeeInsert);
                    if(insertEmployee > 0){
                        clearField();
                        keywordTF.setText("");
                        loadTable(null);
                        JOptionPane.showMessageDialog(null,"Berhasil Menambah Employee");
                    }else{
                        JOptionPane.showMessageDialog(null,"Gagal Menambah Employee");
                    }   
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"Tidak Bisa Menambah Employee");
        }
       
    }//GEN-LAST:event_buttonAddMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        TableModel model = jTable1.getModel();
        String employeeId = model.getValueAt(selectedRow, 0).toString();
        String employeeName = model.getValueAt(selectedRow, 1).toString();
        String roleName = model.getValueAt(selectedRow, 2).toString();
        String gender = model.getValueAt(selectedRow, 3).toString();
        String birthPlace = model.getValueAt(selectedRow, 4).toString();
        String birthDate = model.getValueAt(selectedRow, 5).toString();
        String phoneNumber = model.getValueAt(selectedRow, 6).toString();
        String address = model.getValueAt(selectedRow, 7).toString();
        String joinDate = model.getValueAt(selectedRow, 8).toString();
        employeeNameTF.setText(employeeName);
        phoneNumberTF.setText(phoneNumber);
        employeeIdTF.setText(employeeId);
        roleNameTF.setText(roleName);
        genderTF.setText(gender);
        textAreaAddress.setText(address);
        joinDateTF.setText(joinDate);
        birthDateTF.setText(birthDate);
        birthPlaceTF.setText(birthPlace);
    }//GEN-LAST:event_jTable1MouseClicked

    private void buttonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClearMouseClicked
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_buttonClearMouseClicked

    private void buttonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDeleteMouseClicked
        // TODO add your handling code here:
        String employeeId = employeeIdTF.getText();
        if(!employeeId.isEmpty()){
            int id = Integer.parseInt(employeeId);
            int deleteEmployee = employeeDao.delete(id);
            if(deleteEmployee == 1){
                clearField();
                loadTable(null); 
                JOptionPane.showMessageDialog(null,"Berhasil Hapus");
            }
        }
    }//GEN-LAST:event_buttonDeleteMouseClicked

    private void buttonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonUpdateMouseClicked
        // TODO add your handling code here:
        String employeeId = employeeIdTF.getText();
        String employeeName = employeeNameTF.getText();
        String phoneNumber = phoneNumberTF.getText();
        
        JOptionPane.showMessageDialog(null,employeeId);
        if(!employeeId.isEmpty()){
            if(employeeName.isEmpty()){
                JOptionPane.showMessageDialog(null,"Nama Employee tidak boleh kosong");
                employeeNameTF.requestFocus();
            }else if(phoneNumber.isEmpty()){
                JOptionPane.showMessageDialog(null,"No. Telp tidak boleh kosong");
                phoneNumberTF.requestFocus();
            }else{
                int id = Integer.parseInt(employeeIdTF.getText());
                EmployeeModel dataUpdateEmployee = new EmployeeModel();
                dataUpdateEmployee.setName(employeeName);
                dataUpdateEmployee.setPhoneNumber(phoneNumber);
                dataUpdateEmployee.setId(id);
                
                EmployeeModel daoFindOneById = new EmployeeModel();
                daoFindOneById.setId(id);
                
                EmployeeModel previousEmployee = employeeDao.findOneById(daoFindOneById);
                if(previousEmployee == null){
                    JOptionPane.showMessageDialog(null,"Employee Tidak Ditemukan");
                }else{
                    if(previousEmployee.getName().equals(dataUpdateEmployee.getName())){
                        int updateEmployee = employeeDao.update(dataUpdateEmployee);
                        if(updateEmployee > 0){
                            clearField();
                            loadTable(null);
                            JOptionPane.showMessageDialog(null,"Berhasil Mengubah Employee");
                        }else{
                            JOptionPane.showMessageDialog(null,"Gagal Mengubah Employee");
                        } 
                    }else{
                        EmployeeModel findOneEmployeeByName = employeeDao.findOneByName(dataUpdateEmployee);
                        if(findOneEmployeeByName != null){
                            JOptionPane.showMessageDialog(null,"Nama Employee Sudah Ada");
                        }else{
                            int updateDataEmployee = employeeDao.update(dataUpdateEmployee);
                            if(updateDataEmployee > 0){
                                clearField();
                                loadTable(null);
                                JOptionPane.showMessageDialog(null,"Berhasil Mengubah Employee");
                            }else{
                                JOptionPane.showMessageDialog(null,"Gagal Mengubah Employee");
                            }   
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_buttonUpdateMouseClicked

    private void keywordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordTFActionPerformed

    private void keywordTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keywordTFKeyReleased
        // TODO add your handling code here:
        String keyword = keywordTF.getText();
        if(!keyword.equals("")){
            List<EmployeeModel> employees = employeeDao.search(keyword);
            loadTable(employees);
        }else{
            loadTable(null);
        } 
    }//GEN-LAST:event_keywordTFKeyReleased

    private void keywordTFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keywordTFMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordTFMouseEntered

    private void keywordTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keywordTFMouseClicked
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_keywordTFMouseClicked

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void ToHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToHomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ToHomeMouseClicked

    private void ToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToHomeActionPerformed
        this.dispose();
        //menampilkan gui Menu
        new MenuView().start();
    }//GEN-LAST:event_ToHomeActionPerformed

    private void roleNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleNameTFActionPerformed

    private void joinDateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinDateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinDateTFActionPerformed

    private void birthPlaceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthPlaceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthPlaceTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ToHome;
    private javax.swing.JTextField birthDateTF;
    private javax.swing.JTextField birthPlaceTF;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JTextField employeeIdTF;
    private javax.swing.JTextField employeeNameTF;
    private javax.swing.JTextField genderTF;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelJoinDate;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTTL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField joinDateTF;
    private javax.swing.JTextField keywordTF;
    private java.awt.Panel panel1;
    private java.awt.Panel panel3;
    private javax.swing.JTextField phoneNumberTF;
    private javax.swing.JTextField roleNameTF;
    private java.awt.TextArea textAreaAddress;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void dispose(){
        // TODO add your handling code here:
        employeeDao.closeConnection();
        super.dispose();
    }
    
    public void start(){
        this.setTitle("Employee Master");
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setResizable(false); // fixed width
        this.setLocationRelativeTo(null); // Set JFrame to center of Screenn
        
        this.addWindowListener( new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JFrame frame = (JFrame)e.getSource();

                int result = JOptionPane.showConfirmDialog(
                    frame,
                    "Are you sure you want to exit the application?",
                    "Exit Application",
                    JOptionPane.YES_NO_OPTION);

                if (result == JOptionPane.YES_OPTION){
                    employeeDao.closeConnection();
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    System.exit(0);
                }
            }
        });
        // TODO add your custom frame code here:
        loadTable(null);
       
        this.setVisible( true );
    }
    
    public void loadTable(List<EmployeeModel> employees) {
        if(employees == null){
            employees = employeeDao.findAll();
        }
        EmployeeTableModel employeeTableModel = new EmployeeTableModel(employees);
        
        jTable1.setModel(employeeTableModel);
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTable1.getModel());
        jTable1.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
//        sortKeys.add(new RowSorter.SortKey(3, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
    }
    
    public void clearField(){
        employeeNameTF.setText("");
        phoneNumberTF.setText("");
        roleNameTF.setText("");
        employeeIdTF.setText("");
        keywordTF.setText("");
    }
}
