/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.views;

/**
 *
 * @author Jimmi iskandar
 */
public class ItemView extends javax.swing.JFrame {

    /**
     * Creates new form itemsview
     */
    public ItemView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dashbord = new javax.swing.JPanel();
        iditem = new javax.swing.JLabel();
        textiditem = new javax.swing.JTextField();
        namaitem = new javax.swing.JLabel();
        textnamaitem = new javax.swing.JTextField();
        stockitem = new javax.swing.JLabel();
        textstockitem = new javax.swing.JTextField();
        texthargaitem = new javax.swing.JTextField();
        hargaitem = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tambahitem = new javax.swing.JButton();
        deleteitem = new javax.swing.JButton();
        edititem = new javax.swing.JButton();
        textcariitem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        clearitem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));

        header.setPreferredSize(new java.awt.Dimension(800, 60));
        header.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Gautami", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Master Items");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 140, 60));

        header.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        dashbord.setBackground(new java.awt.Color(255, 255, 255));

        iditem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iditem.setText("Id Item");
        iditem.setPreferredSize(new java.awt.Dimension(35, 15));

        textiditem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        textiditem.setEnabled(false);
        textiditem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textiditemActionPerformed(evt);
            }
        });

        namaitem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        namaitem.setText("Nama Item");
        namaitem.setPreferredSize(new java.awt.Dimension(35, 15));

        textnamaitem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        textnamaitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnamaitemActionPerformed(evt);
            }
        });

        stockitem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stockitem.setText("Stock");

        textstockitem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        textstockitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textstockitemActionPerformed(evt);
            }
        });

        texthargaitem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        texthargaitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texthargaitemActionPerformed(evt);
            }
        });

        hargaitem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hargaitem.setText("Harga");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tambahitem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tambahitem.setForeground(new java.awt.Color(51, 51, 51));
        tambahitem.setText("Tambah");
        tambahitem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tambahitem.setBorderPainted(false);
        tambahitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahitemActionPerformed(evt);
            }
        });

        deleteitem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteitem.setForeground(new java.awt.Color(51, 51, 51));
        deleteitem.setText("Delete");
        deleteitem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        deleteitem.setBorderPainted(false);
        deleteitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteitemActionPerformed(evt);
            }
        });

        edititem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        edititem.setForeground(new java.awt.Color(51, 51, 51));
        edititem.setText("Edit");
        edititem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        edititem.setBorderPainted(false);
        edititem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edititemActionPerformed(evt);
            }
        });

        textcariitem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        textcariitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcariitemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cari Data");

        clearitem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clearitem.setForeground(new java.awt.Color(51, 51, 51));
        clearitem.setText("Clear");
        clearitem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        clearitem.setBorderPainted(false);
        clearitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearitemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashbordLayout = new javax.swing.GroupLayout(dashbord);
        dashbord.setLayout(dashbordLayout);
        dashbordLayout.setHorizontalGroup(
            dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashbordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(dashbordLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dashbordLayout.createSequentialGroup()
                            .addComponent(hargaitem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addComponent(texthargaitem, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dashbordLayout.createSequentialGroup()
                            .addComponent(stockitem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addComponent(textstockitem, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dashbordLayout.createSequentialGroup()
                            .addComponent(namaitem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addComponent(textnamaitem, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dashbordLayout.createSequentialGroup()
                            .addComponent(iditem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addComponent(textiditem, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashbordLayout.createSequentialGroup()
                        .addComponent(tambahitem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(edititem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteitem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearitem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textcariitem, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, Short.MAX_VALUE))
        );
        dashbordLayout.setVerticalGroup(
            dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashbordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iditem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textiditem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaitem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textnamaitem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockitem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textstockitem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaitem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texthargaitem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahitem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteitem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edititem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearitem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(dashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textcariitem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(dashbord, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textiditemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textiditemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textiditemActionPerformed

    private void textnamaitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnamaitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnamaitemActionPerformed

    private void textstockitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textstockitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textstockitemActionPerformed

    private void texthargaitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texthargaitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texthargaitemActionPerformed

    private void tambahitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahitemActionPerformed

    private void deleteitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteitemActionPerformed

    private void edititemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edititemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edititemActionPerformed

    private void textcariitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcariitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcariitemActionPerformed

    private void clearitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearitemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearitem;
    private javax.swing.JPanel dashbord;
    private javax.swing.JButton deleteitem;
    private javax.swing.JButton edititem;
    private javax.swing.JLabel hargaitem;
    private javax.swing.JPanel header;
    private javax.swing.JLabel iditem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel namaitem;
    private javax.swing.JLabel stockitem;
    private javax.swing.JButton tambahitem;
    private javax.swing.JTextField textcariitem;
    private javax.swing.JTextField texthargaitem;
    private javax.swing.JTextField textiditem;
    private javax.swing.JTextField textnamaitem;
    private javax.swing.JTextField textstockitem;
    // End of variables declaration//GEN-END:variables
}
