/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application.views;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;

import javax.swing.JFrame;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author she
 */
public class StatusQmChartView extends javax.swing.JFrame {

    /**
     * Creates new form statusQmChartView
     */
    public StatusQmChartView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatusQmChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatusQmChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatusQmChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatusQmChartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatusQmChartView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void start(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        // Data dummy untuk status kutipan per tahun dalam Rupiah
        dataset.addValue(2000, "2022", "Jan");
        dataset.addValue(2500, "2022", "Feb");
        dataset.addValue(3000, "2022", "Mar");
        dataset.addValue(2800, "2022", "Apr");
        dataset.addValue(3200, "2022", "May");
        dataset.addValue(3000, "2022", "Jun");
        dataset.addValue(2800, "2022", "Jul");
        dataset.addValue(2600, "2022", "Aug");
        dataset.addValue(2900, "2022", "Sep");
        dataset.addValue(2500, "2022", "Ock");
        dataset.addValue(2700, "2022", "Nov");
        dataset.addValue(3100, "2022", "Des");

        dataset.addValue(1500, "2021", "Jan");
        dataset.addValue(1800, "2021", "Feb");
        dataset.addValue(2000, "2021", "Mar");
        dataset.addValue(1800, "2021", "Apr");
        dataset.addValue(2200, "2021", "May");
        dataset.addValue(2000, "2021", "Jun");
        dataset.addValue(1900, "2021", "Jul");
        dataset.addValue(1700, "2021", "Aug");
        dataset.addValue(2100, "2021", "Sep");
        dataset.addValue(2000, "2021", "Ock");
        dataset.addValue(2200, "2021", "Nov");
        dataset.addValue(2400, "2021", "Des");
        JFreeChart chart = ChartFactory.createLineChart(
                "Status Quotation per Tahun",
                "Bulan",
                "Nilai (M)",
                dataset,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );

        CategoryPlot plot = (CategoryPlot) chart.getPlot();
        CategoryAxis categoryAxis = plot.getDomainAxis();
        categoryAxis.setLowerMargin(0.05);
        categoryAxis.setUpperMargin(0.05);

        NumberAxis valueAxis = (NumberAxis) plot.getRangeAxis();
        valueAxis.setStandardTickUnits(NumberAxis.createStandardTickUnits());
        valueAxis.setNumberFormatOverride(new DecimalFormat("#,###"));

        plot.getRenderer().setBaseItemLabelGenerator(new StandardCategoryItemLabelGenerator("{2}", new DecimalFormat("#,###")));
        plot.getRenderer().setBaseItemLabelsVisible(true);

        JFrame frame = new JFrame("Chart Example");
        frame.setPreferredSize(new Dimension(800, 600));
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setResizable(false); // fixed width
        

        ChartPanel chartPanel = new ChartPanel(chart);
        frame.getContentPane().add(chartPanel);
        frame.pack();
        frame.setLocationRelativeTo(null); // Set JFrame to center of Screen
        frame.setVisible(true);
    }
    
    
}
